on: [push]

jobs:

  deploy:

    runs-on: ubuntu-latest
    name: Deploy Quickbase formulas to an application

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy formula action step
        id: deploy
        uses: cpliakas/quickbase-deploy-action@main
        env:
          QUICKBASE_USER_TOKEN: ${{ secrets.QUICKBASE_USER_TOKEN }}
        with:
          realm-hostname: cpliakas.quickbase.com
