on: [push]

jobs:

  deploy:

    runs-on: ubuntu-latest
    name: Deploy Quickbase formulas to an application

    steps:

      - name: Deploy formula action step
        id: deploy
        uses: cpliakas/quickbase-action@main
        env:
          QUICKBASE_USER_TOKEN: ${{ secrets.QUICKBASE_USER_TOKEN }}
        with:
          realm-hostname: cpliakas.quickbase.com
          app-id: brgidnacu

      - name: Print Quickbase CLI version action step
        run: echo "Version ${{ steps.deploy.outputs.version }}"
