name: Test

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest
    name: Test Quickbase formulas

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test formula action step
        id: test
        uses: cpliakas/quickbase-test-action@main
        env:
          QUICKBASE_USER_TOKEN: ${{ secrets.QUICKBASE_USER_TOKEN }}
        with:
          realm-hostname: cpliakas.quickbase.com
